# Generated by Django 5.2.7 on 2026-09-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
