# Generated by Django 5.2.7 on 2026-09-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatsession_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='introduction_complete',
            field=models.BooleanField(default=False),
        ),
    ]
