# Generated by Django 5.2.7 on 2026-09-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatsession_introduction_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('bot', 'Bot'), ('operator', 'Operador'), ('closed', 'Encerrada')], default='bot', max_length=10),
        ),
    ]
