# Generated by Django 5.2.7 on 2026-09-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aitokenusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitokenusage',
            options={'verbose_name': 'Consumo de tokens da IA', 'verbose_name_plural': 'Consumo de tokens da IA'},
        ),
    ]
