# Generated by Django 5.2.6 on 2025-10-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_abre', models.TimeField(default='08:00')),
                ('horario_fecha', models.TimeField(default='18:00')),
                ('dias_funcionamento', models.CharField(default='0,1,2,3,4,5,6', help_text='Dias da semana abertos, separados por vírgula. 0=Segunda, 6=Domingo', max_length=20)),
                ('theme_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_loja', models.CharField(default='Minha Loja', max_length=100)),
                ('descricao_loja', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(default='21976857525', max_length=20)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_endereco', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
        ),
    ]
