# Generated by Django 5.2.7 on 2026-08-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Minha Empresa', max_length=100)),
                ('email_contato', models.EmailField(default='contato@empresa.com', max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('dominio', models.CharField(default='meusite.com', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='cpf_ou_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='aberto',
            field=models.BooleanField(default=True, help_text='Indica se a loja está aberta ou fechada'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bandeiras_cartao_credito',
            field=models.CharField(blank=True, help_text='Ex: Visa, MasterCard, Amex', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bandeiras_cartao_debito',
            field=models.CharField(blank=True, help_text='Ex: Visa, MasterCard', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='color_theme',
            field=models.CharField(default='#DD7B0A', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='cpf_ou_cnpj',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='credito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='debito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='dinheiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='exibicao_produtos',
            field=models.CharField(default='1', help_text='Tipo de exibição dos produtos', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='facebook_pixel',
            field=models.CharField(blank=True, help_text='ID do Facebook Pixel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='fotocapa/'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotoperfil/'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='googleanalytics',
            field=models.CharField(blank=True, help_text='ID do Google Analytics', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='instagram_pixel',
            field=models.CharField(blank=True, help_text='ID do Instagram Pixel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='nome_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='pagamento_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='pix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='segmento',
            field=models.CharField(blank=True, help_text='Segmento de negócio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Subdomínio da loja', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tipo_catalogo',
            field=models.CharField(default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, help_text='Tipo da chave PIX', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='dias_funcionamento',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='OBSOLETO: Use HorarioFuncionamento. Dias da semana abertos, separados por vírgula. 0=Segunda, 6=Domingo', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='horario_abre',
            field=models.TimeField(default='08:00', help_text='OBSOLETO: Use HorarioFuncionamento'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='horario_fecha',
            field=models.TimeField(default='18:00', help_text='OBSOLETO: Use HorarioFuncionamento'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='nome_loja',
            field=models.CharField(default='Seu nome completo', max_length=100),
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('horario_abre', models.TimeField()),
                ('horario_fecha', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_especifica', models.DateField(blank=True, help_text='Para feriados/eventos específicos', null=True)),
                ('descricao', models.CharField(blank=True, help_text='Ex: Feriado, Promoção especial', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['dia_semana', 'horario_abre'],
                'unique_together': {('tenant', 'dia_semana', 'data_especifica')},
            },
        ),
    ]
