# Generated by Django 5.2.7 on 2026-08-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_configuracao_tenant_cpf_ou_cnpj_tenant_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
