# Generated by Django 5.2.7 on 2026-08-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_configuracao_valor_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='access_token_mercadopago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='public_key_mercadopago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
