# Generated by Django 5.2.7 on 2026-08-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_configuracao_access_token_mercadopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='webhook_secret_mercadopago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
