# Generated by Django 5.2.7 on 2026-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_configuracao_webhook_secret_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dias_gratuitos',
            field=models.IntegerField(default=30),
        ),
    ]
