# Generated by Django 5.2.7 on 2026-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_configuracao_access_token_mercadopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='front_page',
            field=models.ImageField(blank=True, null=True, upload_to='front_pages/'),
        ),
    ]
