# Generated by Django 5.2.7 on 2026-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_configuracao_bairro_configuracao_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
