# Generated by Django 5.2.7 on 2026-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_configuracao_cnpj_configuracao_inscricao_estadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='nome_razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
