# Generated by Django 5.2.7 on 2026-09-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_configuracao_nome_razao_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
