# Generated by Django 5.2.7 on 2026-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_configuracao_logo_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='aberto',
            field=models.BooleanField(default=False),
        ),
    ]
