# Generated by Django 5.2.7 on 2026-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_tenantsettings_ai_orientations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='chamar_whatsapp',
            field=models.BooleanField(default=True, help_text='Exibe o botão para enviar a sacola pelo WhatsApp'),
        ),
    ]
