# Generated by Django 5.2.7 on 2026-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenantsettings_chamar_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='tag_google_analytics',
            field=models.CharField(blank=True, help_text='Tag do Google Analytics', max_length=100, null=True),
        ),
    ]
