# Generated by Django 5.2.7 on 2026-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenantsettings_tag_google_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='bot_ativo_ia',
            field=models.BooleanField(default=False, help_text='Abre o chat automaticamente ao entrar na loja.', verbose_name='Bot ativo com IA'),
        ),
    ]
