# Generated by Django 5.2.7 on 2026-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_tenantsettings_bot_ativo_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='tipo_operacao',
            field=models.CharField(choices=[('delivery', 'Alimentação / Delivery'), ('varejo', 'Comércio / Venda de produtos')], default='varejo', max_length=20, verbose_name='Fluxo de pedidos'),
        ),
    ]
