# Generated by Django 5.2.7 on 2026-09-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenantsettings_tipo_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='google_analytics_property_id',
            field=models.CharField(blank=True, default='', help_text='ID numérico da propriedade GA4 usado para consultar relatórios.', max_length=30),
        ),
    ]
