# Generated by Django 5.2.7 on 2026-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='Data limite de acesso (trial ou assinatura)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
