# Generated by Django 5.2.7 on 2026-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_user_email_confirmation_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoentrega',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
