# Generated by Django 5.2.7 on 2026-09-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0019_tenantsettings_tipo_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.CharField(choices=[('novo', 'Novo'), ('confirmado', 'Confirmado'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('mensagem', models.TextField(max_length=1000)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_whatsapp', to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'status_pedido'), name='whatsapp_mensagem_unica_por_tenant_status')],
            },
        ),
    ]
