# Generated by Django 5.2.7 on 2026-09-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenantsettings_tipo_operacao'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('desconectado', 'Não conectado'), ('preparando', 'Preparando conexão'), ('aguardando_qr', 'Aguardando QR Code'), ('conectado', 'Conectado'), ('erro', 'Erro de comunicação')], default='desconectado', max_length=20)),
                ('numero_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('conectado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configuracao', to='tenants.tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='MensagemAutomatica',
        ),
    ]
