# Generated by Django 5.2.7 on 2026-09-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenantsettings_tipo_operacao'),
        ('whatsapp', '0002_whatsappconfiguracao_delete_mensagemautomatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cenario', models.CharField(choices=[('delivery', 'Alimentação / Delivery'), ('varejo', 'Comércio / Venda de produtos')], max_length=20)),
                ('status_pedido', models.CharField(max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('mensagem', models.TextField(max_length=1200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_processo_whatsapp', to='tenants.tenant')),
            ],
            options={
                'ordering': ['cenario', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'cenario', 'status_pedido'), name='whatsapp_processo_unico_tenant_cenario_status')],
            },
        ),
    ]
