# Generated by Django 5.2.7 on 2026-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_mensagemprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemprocesso',
            name='cenario',
            field=models.CharField(choices=[('delivery', 'Alimentação / Delivery'), ('varejo', 'Comércio / Venda de produtos'), ('pagamento', 'Pagamento')], max_length=20),
        ),
    ]
