# Generated by Django 5.2.7 on 2026-09-01 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0007_remove_configuracao_access_token_mercadopago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_cobranca', models.CharField(help_text='Identificador único da cobrança (ex: ID do gateway de pagamento)', max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado'), ('in_process', 'Em análise')], default='pending', max_length=20)),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pix_qr_code', models.TextField(blank=True, null=True)),
                ('pix_qr_code_base64', models.TextField(blank=True, null=True)),
                ('dias_creditados', models.PositiveIntegerField(default=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('resposta_bruta', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
