# Custom user model
AUTH_USER_MODEL = 'customers.User'
"""
Django settings for burger project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega o .env do diretório raiz; variáveis já definidas no ambiente têm prioridade.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

####################  MERCADO PAGO ==============================
MERCADO_PAGO_ACCESS_KEY = os.getenv('MERCADO_PAGO_ACCESS_KEY', '')
MERCADO_PAGO_TOKEN = os.getenv('MERCADO_PAGO_TOKEN', '')
##################################################################

# ALLOWED_HOSTS = [
#     host.strip()
#     for host in os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')
#     if host.strip()
# ]

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1').split(',')
    if host.strip()
]
if DEBUG and '.localhost' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.localhost')

PUBLIC_SITE_URL = os.getenv('PUBLIC_SITE_URL', '').strip().rstrip('/')


# Necessário para hosts externos (ex.: ngrok) que fazem POST via HTTPS.
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    *[
        origin.strip()
        for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
        if origin.strip()
    ],
]


# Habilite somente quando o proxy confiável sobrescreve X-Forwarded-Proto
# e o servidor de origem não aceita conexões diretas de clientes.
if os.getenv('DJANGO_TRUST_PROXY_HEADERS', 'False').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuração de Logs para aparecer no terminal e gravar em arquivo físico.
# Em produção, o diretório pode não ser gravável pelo usuário do processo. Nesse caso,
# o sistema usa apenas o console para evitar falha na inicialização do Django.
LOG_DIR = BASE_DIR / 'logs'

try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    LOG_DIR = Path('/tmp') / 'burger_logs'
    LOG_DIR.mkdir(parents=True, exist_ok=True)

FILE_HANDLER = {}
if os.access(str(LOG_DIR), os.W_OK):
    FILE_HANDLER = {
        'class': 'logging.FileHandler',
        'filename': str(LOG_DIR / 'log.txt'),
        'formatter': 'simples',
        'encoding': 'utf-8',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simples': {
            'format': '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simples',
        },
        **({'file': FILE_HANDLER} if FILE_HANDLER else {}),
    },
    'root': {
        'handlers': ['console'] + (['file'] if FILE_HANDLER else []),
        'level': 'INFO',
    },
    'loggers': {
        'tenants': {
            'handlers': ['console'] + (['file'] if FILE_HANDLER else []),
            'level': 'DEBUG',
            'propagate': False,
        },
        'tenants.middleware': {
            'handlers': ['console'] + (['file'] if FILE_HANDLER else []),
            'level': 'DEBUG',
            'propagate': True,
        },
        'pagamento': {
            'handlers': ['console'] + (['file'] if FILE_HANDLER else []),
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenants',
    'menu',
    'orders',
    'customers',
    'core',
    'pagamento',
    'analytics',
    'whatsapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'tenants.middleware.TenantMiddleware',
    'tenants.middleware.RootStoreRedirectMiddleware',
    'analytics.middleware.AnalyticsMiddleware',
    #tenants.middleware.TenantDBMiddleware', # Se você estiver usando banco de dados por tenant
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'burger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'customers.contexto.recuperar_tenant_do_contexto',
                'customers.contexto.configuracao_context',
                'customers.contexto.loja_aberta_context',
                'customers.contexto.url_marketplace_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'burger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('DB_NAME', 'master_db'),
        "USER": os.environ['DB_USER'],
        "PASSWORD": os.environ['DB_PASSWORD'],
        "HOST": os.getenv('DB_HOST', 'localhost'),
        "PORT": os.getenv('DB_PORT', '5432'),
    }
}

MERCADOPAGO_WEBHOOK_SECRET = os.getenv('MERCADOPAGO_WEBHOOK_SECRET', '')

####################  CHAT COM IA =================================
AI_CHAT_API_KEY = os.getenv('AI_CHAT_API_KEY', '').strip() or os.getenv('OPENAI_API_KEY', '').strip()
AI_CHAT_API_URL = os.getenv('AI_CHAT_API_URL', 'https://api.openai.com/v1/chat/completions')
AI_CHAT_MODEL = os.getenv('AI_CHAT_MODEL', 'gpt-4o-mini')
AI_CHAT_TIMEOUT = int(os.getenv('AI_CHAT_TIMEOUT', '20'))
##################################################################

####################  EVOLUTION API ==============================
EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL', 'http://127.0.0.1:8080').strip().rstrip('/')
EVOLUTION_API_KEY = os.getenv('EVOLUTION_API_KEY', '').strip()
EVOLUTION_API_TIMEOUT = int(os.getenv('EVOLUTION_API_TIMEOUT', '10'))

GOOGLE_STATS_PIN = os.getenv('GOOGLE_STATS_PIN', '1234').strip()
VIAZAP_GOOGLE_ANALYTICS_PROPERTY_ID = os.getenv('VIAZAP_GOOGLE_ANALYTICS_PROPERTY_ID', '').strip()
##################################################################

####################  E-MAIL (recuperação de senha, etc.) =======
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
# Só usa o backend de console (sem envio real) se nenhum EMAIL_HOST foi configurado.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
##################################################################

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "core" / "assets"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


##############################WHITENOISE##############################
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ADICIONAR_RUIDO_EM_FOTOS = True   # muda aqui e afeta tudo
##############################END WHITENOISE###########################
