from orders import panel_views as order_panel
from customers.views_auth import (
    login_view,
    register_view,
    confirm_registration_view,
    novocadastro_view,
    painel_view,
    painel_pedidos_pendentes_count,
    painel_pedidos_dados,
    logout_view,
    painel_home,
    painel_bot_atendimento,
    painel_bot_sessoes,
    painel_bot_mensagens,
    painel_bot_enviar,
    painel_bot_orientacoes,
    painel_bot_alternar_sessao,
    painel_categorias,
    painel_categorias_add,
    painel_categoria_delete,
    painel_categorias_edit,
    painel_produtos,
    painel_produtos_add,
    painel_produto_delete,
    painel_produtos_edit,
    painel_configuracao,
    upload_foto_perfil,
    upload_foto_capa,
    painel_qrcode,
    painel_reduzir_imagens,
    painel_banners,
    painel_banners_add,
    painel_banners_delete,
    painel_banners_edit,
    password_reset_request_view,
    password_reset_confirm_view,
)
 
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from core.views import (
    loja,
    detalhe,
    add_to_cart,
    sacola,
    checkout,
    remover_do_carrinho_ajax,
    atualizar_carrinho_ajax,
    manifest_json,
    cloudflare_dummy,
    image_placeholder,
    checkout_sucesso,
    home_view,
    inicial,
    enviar_suporte,
    loja_ai_chat,
    loja_ai_chat_messages,
    loja_ai_chat_status,
    loja_ai_chat_assumir,
)

from orders.views import pedido_delivery, pedido_balcao, pedido_whatsapp, cadastro_form
from analytics.views import google_stats, relatorio_acessos


urlpatterns = [
    path('admin/', admin.site.urls),
    path('loja/', loja, name='loja'),
    path('loja/datail/<int:produto_id>', detalhe, name='detalhe'),
    path('loja/chat/ia/', loja_ai_chat, name='loja_ai_chat'),
    path('loja/chat/mensagens/', loja_ai_chat_messages, name='loja_ai_chat_messages'),
    path('loja/chat/status/', loja_ai_chat_status, name='loja_ai_chat_status'),
    path('loja/chat/assumir/', loja_ai_chat_assumir, name='loja_ai_chat_assumir'),
    path('suporte/enviar/', enviar_suporte, name='enviar_suporte'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('loja/sacola', sacola, name='sacola'),
    path('loja/checkout', checkout, name='finalizar_pedido'),
    path('carrinho/remover-ajax/', remover_do_carrinho_ajax, name='remover_do_carrinho_ajax'),
    path('atualizar-carrinho/', atualizar_carrinho_ajax, name='atualizar_carrinho_ajax'),
    path('pedido_delivery/', pedido_delivery, name='pedido_delivery'),
    path('pedido_balcao/', pedido_balcao, name='pedido_balcao'),
    path('pedido_whatsapp/', pedido_whatsapp, name='pedido_whatsapp'),
    path('cadastro_form',cadastro_form, name='cadastro_form'),
    path('checkout_sucesso/',checkout_sucesso, name='checkout_sucesso'),
    path('login/', login_view, name='login'),
    path('register/confirm/<uidb64>/<token>/', confirm_registration_view, name='confirm_registration'),
    path('password-reset/', password_reset_request_view, name='password_reset_request'),
    path('password-reset/<uidb64>/<token>/', password_reset_confirm_view, name='password_reset_confirm'),
    path('painel/pedidos', painel_view, name='painel_pedidos'),
    path('painel/pedidos/<int:ordem_id>/cliente/', order_panel.customer, name='pedido_cliente'),
    path('painel/pedidos/<int:ordem_id>/status/', order_panel.status, name='pedido_status'),
    path('painel/pedidos/<int:ordem_id>/cancelar/', order_panel.cancel, name='pedido_cancelar'),
    path('painel/pedidos/<int:ordem_id>/entrega/', order_panel.delivery, name='pedido_tipo_entrega'),
    path('painel/pedidos/<int:ordem_id>/pagamento/', order_panel.payment, name='pedido_pagamento'),
    path('painel/pedidos/<int:ordem_id>/historico/', order_panel.history, name='pedido_historico'),
    path('painel/pedidos/pendentes-count/', painel_pedidos_pendentes_count, name='painel_pedidos_pendentes_count'),
    path('painel/pedidos/dados/', painel_pedidos_dados, name='painel_pedidos_dados'),
    path('painel/home/', painel_home, name='painel_home'),
    path('painel/relatorios/acessos/', relatorio_acessos, name='relatorio_acessos'),
    path('stats/', google_stats, name='google_stats'),
    path('painel/atendimento-ia/', painel_bot_atendimento, name='painel_bot_atendimento'),
    path('painel/atendimento-ia/sessoes/', painel_bot_sessoes, name='painel_bot_sessoes'),
    path('painel/atendimento-ia/mensagens/', painel_bot_mensagens, name='painel_bot_mensagens'),
    path('painel/atendimento-ia/enviar/', painel_bot_enviar, name='painel_bot_enviar'),
    path('painel/atendimento-ia/orientacoes/', painel_bot_orientacoes, name='painel_bot_orientacoes'),
    path('painel/atendimento-ia/alternar-sessao/', painel_bot_alternar_sessao, name='painel_bot_alternar_sessao'),
    path('painel/categorias/', painel_categorias, name='painel_categorias'),
    path('painel/categorias/adicionar/', painel_categorias_add, name='painel_categorias_add'),
    path('painel/categorias/deletar/<int:categoria_id>/', painel_categoria_delete, name='painel_categoria_delete'),
    path('painel/categorias/editar/<int:categoria_id>/', painel_categorias_edit, name='painel_categorias_edit'),
    path('painel/produtos/', painel_produtos, name='painel_produtos'),
    path('painel/produtos/adicionar/', painel_produtos_add, name='painel_produtos_add'),
    path('painel/produtos/deletar/<int:produto_id>/', painel_produto_delete, name='painel_produto_delete'),
    path('painel/produtos/editar/<int:produto_id>/', painel_produtos_edit, name='painel_produtos_edit'),
    path('painel/configuracao/', painel_configuracao, name='painel_configuracao'),  # Ajuste conforme necessário
    path('painel/upload-foto-perfil/', upload_foto_perfil, name='upload_foto_perfil'),
    path('painel/upload-foto-capa/', upload_foto_capa, name='upload_foto_capa'),
    path('painel/qrcode', painel_qrcode, name='painel_qrcode'),
    path('painel/reduzir-imagens/', painel_reduzir_imagens, name='painel_reduzir_imagens'),
    path('painel/whatsapp/', include('whatsapp.urls')),
    path('painel/banners', painel_banners, name='painel_banners'),
    path('painel/banners/adicionar/', painel_banners_add, name='painel_banners_add'),
    path('painel/banners/deletar/<int:banner_id>/', painel_banners_delete, name='painel_banners_delete'),
    path('painel/banners/editar/<int:banner_id>/', painel_banners_edit, name='painel_banners_edit'),
    path('painel/pagamento/', include('pagamento.urls')),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('novocadastro/', novocadastro_view, name='novocadastro'),
    path('manifest.json', manifest_json, name='manifest'),
    path('loja/manifest.json', manifest_json, name='loja_manifest'),  # Para rotas dentro de /loja/
    # Rotas para lidar com Cloudflare CDN em desenvolvimento
    path('cdn-cgi/<path:path>', cloudflare_dummy, name='cloudflare_dummy'),
    path('loja/cdn-cgi/<path:path>', cloudflare_dummy, name='loja_cloudflare_dummy'),
    path('placeholder.png', image_placeholder, name='image_placeholder'),
    path('', home_view, name='home_view'),
  #  path('', RedirectView.as_view(url='/loja/')),  # redireciona a raiz
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
