# Generated by Django 5.2.7 on 2026-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('tenants', '0007_remove_configuracao_access_token_mercadopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_extra',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='integrado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ordem_exibicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('banner_pc', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner_mobile', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/')),
                ('ordem', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='menu.produto')),
            ],
        ),
    ]
