# Generated by Django 5.2.7 on 2026-09-05 14:27

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_ordem_category_status_produto_exibir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.upload_banner),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_pc',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.upload_banner),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.upload_produto_imagem),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_extra',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.upload_produto_imagem),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(upload_to=menu.models.upload_produto_galeria),
        ),
    ]
