# Generated by Django 5.2.7 on 2026-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='tx_entrega',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ordem',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da ordem no momento do fechamento', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordemitem',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do produto no momento do pedido', max_digits=10, null=True),
        ),
    ]
