# Generated by Django 5.2.7 on 2026-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordem_tx_entrega_ordem_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='vendedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
