# Generated by Django 5.2.7 on 2026-09-20 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordem_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='concluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('confirmado', 'Confirmado'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='novo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordem',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordem',
            name='tipo_entrega',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada'), ('a_combinar', 'A combinar')], default='a_combinar', max_length=20),
        ),
        migrations.AddField(
            model_name='ordem',
            name='tipo_operacao',
            field=models.CharField(choices=[('delivery', 'Alimentação / Delivery'), ('varejo', 'Comércio / Venda de produtos')], default='', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoStatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('novo', 'Novo'), ('confirmado', 'Confirmado'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=20)),
                ('status_novo', models.CharField(choices=[('novo', 'Novo'), ('confirmado', 'Confirmado'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_status', to='orders.ordem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de status do pedido',
                'verbose_name_plural': 'Históricos de status dos pedidos',
                'ordering': ['alterado_em', 'id'],
            },
        ),
    ]
