# Generated by Django 5.2.7 on 2026-09-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_backfill_order_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='observacoes',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Observações do pedido'),
        ),
    ]
